name = "Combinat"
uuid = "a6b051d1-fc4b-4ede-b53e-347fa9fb9a74"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.0.2"
[compat]
julia = "1"
Primes = "0.5, 0.6"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
